### ISSUE TITLE
Feature Request - Setable Default and CLI overridable posting mode (anonymous vs account)

### ISSUE THREAD

**Issue by fuzzyweapon** [xiaohk/clip2imgur#1]
Currently it seems like one can decide to use this tool to post anonymously until they decide they don't want to.  Then they have to authorize, and then that's the way the tool will be used from then on?

It follows that a fair amount of users would have a reason to sometimes use it to post anonymously and sometimes use it with their account, depending on the individual use case (does the image I'm posting need to be permanent or is it temporal in nature, am I uploading something I don't want tied back to my identity bc I'm sending it to some support person for something that has nothing to do with my imgur account?, etc)

It'd be nice if there was a way to set a default (and change it later), as well as something for the command line that will overwrite the default (e.g. -a for --anonymous, -A for --account).  This way people can choose what their most common case is for their default.

For implementation suggestions for how to set the default?  Nothing wrong with an environment variable!

**Comment by xiaohk** [comment]
@fuzzyweapon good idea! I will add this feature. I am thinking of the following design:

- If user has set up the account:
    Default is posting to the account, but use `-a` to post anonymously
- If user has not set up the account:
    Default and `-a` are both posting anonymously

**Comment by KnifeFed** [comment]
Did you ever get to this? I would like to use this in a script but can't right now because it needs manual input to do an anonymous upload.

**Comment by ghost** [comment]
For anybody looking into this, you can just use

`printf "no" | clip2imgur`

**Comment by xiaohk** [comment]
Thank you all!! This issue if finally fixed in version 0.9.3. You can use `clip2imgur -a` to post images anonymously.
